name: encrypt-secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret in plain-text'
        type: string

jobs:
  encrypt_secret:
    uses: bayer-int/DTEF-API-Management/.github/workflows/encrypt-secret.yml@main
    secrets:
      secret: ${{ github.event.inputs.secret }}
      encryption-key-local: ${{ secrets.ENCRYPTION_KEY_LOCAL }}
      encryption-key-nonprod: ${{ secrets.ENCRYPTION_KEY_NONPROD }}
      encryption-key-prod: ${{ secrets.ENCRYPTION_KEY_PROD }}
